M48
; DRILL file {KiCad 7.0.6} date Thu Sep 28 23:10:46 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-28T23:10:46+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
%
G90
G05
T1
X124.5Y-55.5
X159.0Y-55.5
T2
X124.5Y-60.0
X159.0Y-60.0
T0
M30
